repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0 # Newer tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3 # newer tags https://github.com/timothycrosley/isort/releases
    hooks:
      - id: isort
