[tool.black]
target-version = ['py37', 'py38', 'py39']
skip-string-normalization = true
exclude = ['vorwaerts/migrations', '.venv']

[tool.isort]
force_single_line = true
lines_after_imports = 2
include_trailing_comma = true
line_length = 88
skip_glob = ["*/migrations/*.py", "__pycache__", '.venv']
