# Generated by Django 3.2.8 on 2021-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorwaerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedad',
            old_name='image_name',
            new_name='file_id',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='block_id',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='height',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='width',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='x',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='y',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
