# Generated by Django 3.2.8 on 2021-11-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorwaerts', '0002_auto_20211102_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='newspaper_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', related_query_name='advertisement', to='vorwaerts.newspaperpage'),
        ),
    ]
