# Generated by Django 4.0.2 on 2022-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorwaerts', '0003_alter_classifiedad_newspaper_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='ocr_confidence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
